// data.js — Flashcard MCQ data (160 entries).
// Loaded BEFORE app.js via <script src="./data.js"> so the `originalData`
// global is available to app.js at init time. Classic script (not
// <script type="module">) so the app still works when opened directly
// from file:// — see index.html for the load order comment.
//
// Each entry shape:
//   { q: "question text", a: "answer text", wikiTitle: "Wikipedia article title" }
//   OR
//   { q: "question text", a: "answer text", noImage: true }   // suppress image

const originalData = [
    { q: "The first UN women ambassador of Pakistan", a: "Maliha Lodhi", wikiTitle: "Maliha Lodhi" },
    { q: "The Indus river originates in China near", a: "Lake Manasarovar", wikiTitle: "Lake Manasarovar" },
    { q: "FriendShip gate is located at", a: "Torkham Border", wikiTitle: "Torkham Border" },
    { q: "Wakhan corridor connects", a: "Afghanistan & China", wikiTitle: "Wakhan Corridor" },
    { q: "Height of Mount Vinson", a: "4892 meters", wikiTitle: "Mount Vinson" },
    { q: "Pakistan Gate is the border between", a: "Iran and Pakistan", wikiTitle: "Pakistan" },
    { q: "Which Continent was referred as Dark Continent", a: "Africa", wikiTitle: "Africa" },
    { q: "Author of Harry Potter book series", a: "J.K. Rowling", wikiTitle: "J. K. Rowling" },
    { q: "US Independence day", a: "4th July 1776", wikiTitle: "United States Declaration of Independence" },
    { q: "Continent Australia is also called as", a: "Oceania", wikiTitle: "Oceania" },
    { q: "Philately is the study of", a: "Stamp collecting", wikiTitle: "Philately" },
    { q: "Pisciculture is the study of", a: "Fish farming", wikiTitle: "Aquaculture" },
    { q: "Telepathy is the study of", a: "Transmission of thoughts directly between minds.", wikiTitle: "Telepathy" },
    { q: "Cryptography is the study of", a: "Secret Writing", wikiTitle: "Cryptography" },
    { q: "Diamer basha dam is on river", a: "Indus", wikiTitle: "Indus River" },
    { q: "City of Saints", a: "Multan", wikiTitle: "Multan" },
    { q: "State of matter with highest kinetic energy", a: "Gas", wikiTitle: "Gas" },
    { q: "Evaporation is", a: "Cooling Process", wikiTitle: "Evaporation" },
    { q: "Pakistan and Tajikistan are separated by", a: "Wakhan Corridor", wikiTitle: "Wakhan Corridor" },
    { q: "NATO was formed in", a: "1949", wikiTitle: "NATO" },
    { q: "The Strategic Arms Limitation Treaty (SALT-I)", a: "1972", wikiTitle: "Strategic Arms Limitation Talks" },
    { q: "World War II began with Germany attack on", a: "Poland", wikiTitle: "Invasion of Poland" },
    { q: "Covid 19 was officially declared as a Pandemic by WHO in", a: "March 2020", wikiTitle: "COVID-19 pandemic" },
    { q: "What forced US to join World War II", a: "Pearl Harbour Attack by Japan", wikiTitle: "Attack on Pearl Harbor" },
    { q: "Fastest sinking city", a: "Jakarta", wikiTitle: "Jakarta" },
    { q: "Doha agreement", a: "Feb 2020", wikiTitle: "Doha Agreement" },
    { q: "1st OIC meeting", a: "Rabat, Morocco (1969)", wikiTitle: "Organisation of Islamic Cooperation" },
    { q: "2nd OIC meeting", a: "Lahore (1974)", wikiTitle: "Organisation of Islamic Cooperation" },
    { q: "Pakistan officially joined UN on", a: "30 Sep 1947", wikiTitle: "Member states of the United Nations" },
    { q: "Socrates was born in", a: "469 BC", wikiTitle: "Socrates" },
    { q: "Which country invented tank", a: "UK", wikiTitle: "Tank" },
    { q: "World Cancer day", a: "4 Feb", wikiTitle: "World Cancer Day" },
    { q: "Height of K2", a: "8611 meters", wikiTitle: "K2" },
    { q: "Smallest Republic", a: "Nauru", wikiTitle: "Nauru" },
    { q: "Largest Producer & Consumer of Electricity in Islamic world", a: "KSA", wikiTitle: "Saudi Arabia" },
    { q: "Saltiest Ocean", a: "Atlantic", wikiTitle: "Atlantic Ocean" },
    { q: "Gilgit Baltistan got independence", a: "1st Nov 1947", wikiTitle: "Gilgit-Baltistan" },
    { q: "Arabian desert is in", a: "Western Asia", wikiTitle: "Arabian Desert" },
    { q: "Gibraltar strait connects Atlantic ocean and", a: "The Mediterranean Sea", wikiTitle: "Strait of Gibraltar" },
    { q: "Oldest university of Pakistan", a: "University of Punjab", wikiTitle: "University of the Punjab" },
    { q: "Treaty of waitangi was signed between British crown and", a: "Maori Chiefs in 1840", wikiTitle: "Treaty of Waitangi" },
    { q: "Tower Bridge", a: "London", wikiTitle: "Tower Bridge" },
    { q: "Nelson Mandela day", a: "18th July", wikiTitle: "Nelson Mandela" },
    { q: "Psephology is the scientific study of", a: "Elections", wikiTitle: "Psephology" },
    { q: "Peace memorial park in Japan is memorial of", a: "Atomic bomb victims", wikiTitle: "Hiroshima Peace Memorial Park" },
    { q: "Which country has agreed to help the United States locate missing Americans?", a: "Syria", wikiTitle: "Syria" },
    { q: "Which Prophet is known as “Khalilullah” (Friend of Allah)?", a: "Ibrahim as", noImage: true },
    { q: "Which vitamin is primarily produced in the skin in response to sunlight?", a: "D", wikiTitle: "Vitamin D" },
    { q: "Which is the first digital census held in Pakistan?", a: "2023", wikiTitle: "Census in Pakistan" },
    { q: "Which new department has been created in Punjab Police to control crime?", a: "Crime Control Department CCD - 26 feb 2026", wikiTitle: "Punjab Police" },
    { q: "When did US removed sanctions on Syria", a: "July 1 2025", wikiTitle: "Sanctions against Syria" },
    { q: "Asim Munir ranked as five star general on", a: "May 20 2025", wikiTitle: "Asim Munir" },
    { q: "PNSC", a: "Pakistan National Shipping Cooperation", wikiTitle: "Pakistan National Shipping Corporation" },
    { q: "NCCIA was built in", a: "May 3 2024", wikiTitle: "Federal Investigation Agency" },
    { q: "What is the name of the Angel who brings rain?", a: "Mika'il as", noImage: true },
    { q: "Smallest country by area", a: "Vatican City", wikiTitle: "Vatican City" },
    { q: "National day in China", a: "October 1", wikiTitle: "China" },
    { q: "Tourism day", a: "September 27", wikiTitle: "World Tourism Day" },
    { q: "Deepest lake in world", a: "Lake Baikal", wikiTitle: "Lake Baikal" },
    { q: "Pearl of Indian ocean is called", a: "Sri Lanka", wikiTitle: "Sri Lanka" },
    { q: "Only country in the world in which there is Day in one Part and night in the other", a: "Russia", wikiTitle: "Russia" },
    { q: "Motto of UNO", a: "It's your world", wikiTitle: "United Nations" },
    { q: "Currency of Israel", a: "Shekel", wikiTitle: "Israeli new shekel" },
    { q: "Deepest part of Earth", a: "Mariana Trench", wikiTitle: "Mariana Trench" },
    { q: "First war of china between", a: "China and Britain", wikiTitle: "First Opium War" },
    { q: "Headquarters of red cross", a: "Geneva", wikiTitle: "International Committee of the Red Cross" },
    { q: "OIC changed its name to Organisation of Islamic Cooperation in", a: "2011", wikiTitle: "Organisation of Islamic Cooperation" },
    { q: "Which country, on the map of world, appears as \"Long Shoe\"", a: "Italy", wikiTitle: "Italy" },
    { q: "Oldest news agency in the world", a: "AFP", wikiTitle: "Agence France-Presse" },
    { q: "Worlds largest Island", a: "Greenland", wikiTitle: "Greenland" },
    { q: "AFP is the news agency of", a: "France", wikiTitle: "France" },
    { q: "\"Land of the Rising Sun\" is the nickname of which country", a: "Japan", wikiTitle: "Japan" },
    { q: "Which gas is most abundant in the Earth's atmosphere", a: "Nitrogen", wikiTitle: "Nitrogen" },
    { q: "The capital of Canada is", a: "Ottawa", wikiTitle: "Ottawa" },
    { q: "Which is the smallest ocean in the world", a: "Arctic Ocean", wikiTitle: "Arctic Ocean" },
    { q: "Mount Everest, the highest peak in the world, is located in", a: "Nepal", wikiTitle: "Mount Everest" },
    { q: "Which planet is known as the Red Planet", a: "Mars", wikiTitle: "Mars" },
    { q: "The currency of Turkey is", a: "Lira", wikiTitle: "Turkish lira" },
    { q: "The Great Wall of China is approximately how long", a: "21,196 km", wikiTitle: "Great Wall of China" },
    { q: "\"Reuters\" is the famous news agency of", a: "United Kingdom", wikiTitle: "Reuters" },
    { q: "Headquarter of Amnesty International", a: "London", wikiTitle: "Amnesty International" },
    { q: "Total member states of UNO", a: "193", wikiTitle: "Member states of the United Nations" },
    { q: "The largest continent of the world", a: "Asia", wikiTitle: "Asia" },
    { q: "The city of seven hills", a: "Rome", wikiTitle: "Rome" },
    { q: "\"Kangaroo\" is the national animal of", a: "Australia", wikiTitle: "Kangaroo" },
    { q: "The official language of Brazil", a: "Portuguese", wikiTitle: "Portuguese language" },
    { q: "Which country has the largest number of volcanoes", a: "Indonesia", wikiTitle: "Indonesia" },
    { q: "The permanent secretariat of SAARC is located in", a: "Kathmandu", wikiTitle: "South Asian Association for Regional Cooperation" },
    { q: "Suez Canal connects", a: "Mediterranean Sea and Red Sea", wikiTitle: "Suez Canal" },
    { q: "\"Land of Thousand Lakes\"", a: "Finland", wikiTitle: "Finland" },
    { q: "The longest river in the world", a: "Nile", wikiTitle: "Nile" },
    { q: "Headquarters of NATO is located in", a: "Brussels", wikiTitle: "NATO" },
    { q: "The currency of Japan", a: "Yen", wikiTitle: "Japanese yen" },
    { q: "The highest waterfall in the world", a: "Angel Falls", wikiTitle: "Angel Falls" },
    { q: "The parliament of Japan is called", a: "Diet", wikiTitle: "National Diet Building" },
    { q: "\"Land of Maple Leaf\" is the nickname of", a: "Canada", wikiTitle: "Canada" },
    { q: "Which country is called the \"Playground of Europe\"", a: "Switzerland", wikiTitle: "Switzerland" },
    { q: "The largest ocean of the world", a: "Pacific Ocean", wikiTitle: "Pacific Ocean" },
    { q: "\"Kyodo\" is the news agency of", a: "Japan", wikiTitle: "Kyodo News" },
    { q: "The International Court of Justice is located in", a: "The Hague (Netherlands)", wikiTitle: "International Court of Justice" },
    { q: "Headquarters of INTERPOL is located in", a: "Lyon (France)", wikiTitle: "Interpol" },
    { q: "The currency of Malaysia", a: "Ringgit", wikiTitle: "Malaysian ringgit" },
    { q: "Which country is known as the \"Land of White Elephants\"", a: "Thailand", wikiTitle: "Thailand" },
    { q: "The largest hot desert in the world", a: "Sahara Desert", wikiTitle: "Sahara" },
    { q: "The world's oldest written constitution is of", a: "USA", wikiTitle: "Constitution of the United States" },
    { q: "Which river crosses the Equator twice", a: "Congo River", wikiTitle: "Congo River" },
    { q: "The largest country in South America is", a: "Brazil", wikiTitle: "Brazil" },
    { q: "The longest mountain range in the world is", a: "Andes", wikiTitle: "Andes" },
    { q: "Headquarter of World Bank is located in", a: "Washington, D.C.", wikiTitle: "World Bank" },
    { q: "Headquarter of Transparency International is in", a: "Berlin", wikiTitle: "Transparency International" },
    { q: "The largest peninsula in the world is", a: "Arabian Peninsula", wikiTitle: "Arabian Peninsula" },
    { q: "Which country is known as the \"Land of Thunderbolts\"", a: "Bhutan", wikiTitle: "Bhutan" },
    { q: "The currency of South Africa", a: "Rand", wikiTitle: "South African rand" },
    { q: "Which country is the largest producer of coffee in the world", a: "Brazil", wikiTitle: "Coffee production in Brazil" },
    { q: "The strait that separates Asia from North America", a: "Bering Strait", wikiTitle: "Bering Strait" },
    { q: "Headquarters of UNESCO is located in", a: "Paris", wikiTitle: "UNESCO" },
    { q: "The country known as the \"Land of Tulips\" is", a: "Netherlands", wikiTitle: "Netherlands" },
    { q: "The highest mountain range in the world is", a: "Himalayas", wikiTitle: "Himalayas" },
    { q: "The capital of Egypt is", a: "Cairo", wikiTitle: "Cairo" },
    { q: "The deepest trench in the Atlantic Ocean is", a: "Puerto Rico Trench", wikiTitle: "Puerto Rico Trench" },
    { q: "Which country is known as the \"Land of a Thousand Elephants\"", a: "Laos", wikiTitle: "Laos" },
    { q: "Headquarter of World Health Organization (WHO) is located in", a: "Geneva (Switzerland)", wikiTitle: "World Health Organization" },
    { q: "The currency of South Korea is", a: "Won", wikiTitle: "South Korean won" },
    { q: "Which country is known as the \"Sugar Bowl of the World\"", a: "Cuba", wikiTitle: "Cuba" },
    { q: "The longest river in Europe is", a: "Volga River", wikiTitle: "Volga River" },
    { q: "Headquarter of International Monetary Fund (IMF) is in", a: "Washington, D.C.", wikiTitle: "International Monetary Fund" },
    { q: "The world's largest producer of tea is", a: "China", wikiTitle: "China" },
    { q: "The capital of New Zealand is", a: "Wellington", wikiTitle: "Wellington" },
    { q: "\"Land of the Midnight Sun\" is the nickname of", a: "Norway", wikiTitle: "Norway" },
    { q: "The country with the longest coastline in the world is", a: "Canada", wikiTitle: "Canada" },
    { q: "\"SPA\" is the official news agency of", a: "Saudi Arabia", wikiTitle: "Saudi Press Agency" },
    { q: "The official residence of the Pope is", a: "Apostolic Palace (Vatican City)", wikiTitle: "Apostolic Palace" },
    { q: "The world's largest inland body of water (or lake) is", a: "Caspian Sea", wikiTitle: "Caspian Sea" },
    { q: "Headquarters of UNICEF is located in", a: "New York", wikiTitle: "UNICEF" },
    { q: "The currency of Russia is", a: "Ruble", wikiTitle: "Russian ruble" },
    { q: "Which country is known as the \"Land of the Golden Fleece\"", a: "Australia", wikiTitle: "Australia" },
    { q: "The capital of Turkey is", a: "Ankara", wikiTitle: "Ankara" },
    { q: "The largest lake in Africa by surface area is", a: "Lake Victoria", wikiTitle: "Lake Victoria" },
    { q: "\"TASS\" is the famous news agency of", a: "Russia", wikiTitle: "TASS" },
    { q: "Which country has the most islands in the world", a: "Sweden", wikiTitle: "Sweden" },
    { q: "The world's highest plateau is", a: "Tibetan Plateau", wikiTitle: "Tibetan Plateau" },
    { q: "Headquarters of Food and Agriculture Organization (FAO) is located in", a: "Rome (Italy)", wikiTitle: "Food and Agriculture Organization" },
    { q: "The currency of Bangladesh is", a: "Taka", wikiTitle: "Bangladeshi taka" },
    { q: "Which country is known as the \"Land of Proteas\"", a: "South Africa", wikiTitle: "South Africa" },
    { q: "The capital of Switzerland is", a: "Bern", wikiTitle: "Bern" },
    { q: "The world's largest country by population is", a: "India", wikiTitle: "India" },
    { q: "\"KCNA\" is the official news agency of", a: "North Korea", wikiTitle: "Korean Central News Agency" },
    { q: "The capital of Ukraine is", a: "Kyiv", wikiTitle: "Kyiv" },
    { q: "Headquarter of Asian Development Bank (ADB) is located in", a: "Manila (Philippines)", wikiTitle: "Asian Development Bank" },
    { q: "The official currency of the United Arab Emirates is", a: "UAE Dirham", wikiTitle: "United Arab Emirates dirham" },
    { q: "Headquarter of World Intellectual Property Organization (WIPO) is located in", a: "Geneva (Switzerland)", wikiTitle: "World Intellectual Property Organization" },
    { q: "The currency of Iran is", a: "Rial", wikiTitle: "Iranian rial" },
    { q: "Which country is known as the \"Land of the Owls\"", a: "Greece", wikiTitle: "Greece" },
    { q: "The capital of Germany is", a: "Berlin", wikiTitle: "Berlin" },
    { q: "The largest river by water volume in the world is", a: "Amazon River", wikiTitle: "Amazon River" },
    { q: "\"MENA\" is the official news agency of", a: "Egypt", wikiTitle: "Middle East News Agency" },
    { q: "Headquarter of International Olympic Committee (IOC) is in", a: "Lausanne (Switzerland)", wikiTitle: "International Olympic Committee" },
    { q: "Which country is known as the \"Land of Cakes\"", a: "Scotland", wikiTitle: "Scotland" },
    { q: "The official currency of Saudi Arabia is", a: "Saudi Riyal", wikiTitle: "Saudi riyal" },
    { q: "The world's largest landlocked country is", a: "Kazakhstan", wikiTitle: "Kazakhstan" }
];
